valor = int(input("Digite um numero: "))
dobro = (valor * 2)
triplo = (valor * 3)
raiz = (valor ** (1 / 2))
print('O dobro de {} é {}!'.format(valor, dobro ))
print('O triplo de {} é {}!'.format(valor, triplo))
print('A raiz de {} é {}!'.format(valor, raiz))